# nixpacks.toml  (repo root)

[phases.setup]
# Force Node instead of Python
nixPkgs = ["nodejs_22"]

[phases.install]
# Install only the server deps
cmds = [
  "cd server && npm ci --omit=dev"
]

[phases.build]
# No build step needed for the Node API
cmds = []

[start]
# How to start the app in production
cmd = "cd server && npm start"
