// web/src/styles.js

// Shared colors & styles (turquoise palette)
export const TURQ = "#14b8a6";
export const TURQ_DARK = "#0ea5a4";

export const sx = {
  app: {
    minHeight: "100vh",
    background: "#f5fbfb",
    color: "#0b1220",
    fontFamily: "Inter, system-ui, Segoe UI, Roboto, sans-serif",
    display: "grid",
    gridTemplateRows: "auto 1fr auto",
  },

  header: {
    padding: "14px 18px",
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    background: "white",
    borderBottom: "1px solid #d7efef",
    position: "sticky",
    top: 0,
    zIndex: 20,
  },
  brand: { display: "flex", alignItems: "center", gap: 10 },
  logo: {
    width: 32,
    height: 32,
    borderRadius: 8,
    background: `linear-gradient(135deg, ${TURQ}, #3dd6c6)`,
    color: "white",
    display: "grid",
    placeItems: "center",
    fontWeight: 800,
    boxShadow: "0 6px 16px rgba(20,184,166,.35)",
  },
  brandName: { fontSize: 18, fontWeight: 700 },
  brandTag: { fontSize: 12, opacity: 0.7 },
  signIn: {
    padding: "8px 12px",
    borderRadius: 8,
    border: `1px solid ${TURQ}`,
    background: "white",
    color: TURQ_DARK,
    cursor: "pointer",
    fontWeight: 600,
  },

  body: {
    display: "grid",
    gridTemplateColumns: "240px 1fr",
    gap: 18,
    padding: 18,
  },
  sidebar: {
    background: "white",
    border: "1px solid #d7efef",
    borderRadius: 12,
    padding: 10,
    display: "grid",
    gap: 6,
    height: "fit-content",
    position: "sticky",
    top: 78,
  },
  sideItem: {
    textAlign: "left",
    padding: "10px 12px",
    borderRadius: 10,
    border: "1px solid #e6f6f5",
    background: "#f6fefe",
    color: "#0b1220",
    cursor: "pointer",
    outline: "none", // 🚫 no black border
  },
  sideItemActive: {
    background: `linear-gradient(135deg, ${TURQ}, #3dd6c6)`,
    borderColor: "#9fe8df",
    color: "white",
    boxShadow: "0 6px 16px rgba(20,184,166,.25)",
    outline: "none", // 🚫 no black border
  },

  main: { display: "grid", gap: 18, alignContent: "start" },
  card: {
    background: "white",
    border: "1px solid #d7efef",
    borderRadius: 14,
    padding: 16,
    boxShadow: "0 6px 16px rgba(20,184,166,.06)",
  },
  successCard: {
    borderColor: "#86efac",
    boxShadow: "0 8px 24px rgba(34,197,94,.15)",
  },
  cardHeader: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 10,
  },
  cardHeaderRow: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
  },
  h2: { margin: 0, fontSize: 20 },
  badge: {
    padding: "4px 8px",
    borderRadius: 999,
    border: "1px solid #e2f7f5",
    fontSize: 12,
  },
  badgeReady: {
    background: "#e6fffc",
    color: TURQ_DARK,
    borderColor: "#baf3ec",
  },
  badgeBusy: {
    background: "#fff7e6",
    color: "#a16207",
    borderColor: "#fde68a",
  },

  desc: { marginTop: 6, color: "#334155" },
  label: { marginTop: 12, marginBottom: 6, display: "block", fontWeight: 600 },
  textarea: {
    width: "100%",
    padding: 12,
    borderRadius: 10,
    border: "1px solid #b7ece7",
    background: "#fcfffe",
    color: "#0b1220",
    fontSize: 14,
    lineHeight: 1.5,
    resize: "none",
  },
  input: {
    width: "100%",
    padding: 10,
    borderRadius: 10,
    border: "1px solid #b7ece7",
    background: "#fcfffe",
    color: "#0b1220",
    marginBottom: 10,
  },
  actions: {
    display: "flex",
    gap: 10,
    alignItems: "center",
    marginTop: 12,
    flexWrap: "wrap",
  },
  primary: {
    padding: "10px 16px",
    borderRadius: 10,
    border: `1px solid ${TURQ}`,
    background: TURQ,
    color: "white",
    fontWeight: 700,
    cursor: "pointer",
    boxShadow: "0 6px 16px rgba(20,184,166,.35)",
  },
  secondary: {
    padding: "10px 16px",
    borderRadius: 10,
    border: "1px solid #b7ece7",
    background: "#f6fffe",
    color: "#0b1220",
    fontWeight: 600,
    cursor: "pointer",
  },

  streamBox: {
    border: "1px solid #e6f6f5",
    borderRadius: 12,
    padding: 12,
    minHeight: 92,
    background: "#f6fffe",
    color: "#0b1220",
  },
  progressLine: { marginBottom: 4 },
  thinking: { marginTop: 6, opacity: 0.9 },

  resultText: { whiteSpace: "pre-wrap", lineHeight: 1.6 },
  note: { marginTop: 8, color: "#334155", fontSize: 13 },
  disclaimer: {
    marginTop: 12,
    fontSize: 12,
    color: "#0f172a",
    background: "#fefce8",
    border: "1px solid #fde68a",
    padding: 10,
    borderRadius: 10,
  },

  footerBar: {
    marginTop: 16,
    paddingTop: 24,
    background: "white",
    borderTop: "1px solid #d7efef",
  },
  footerColumns: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(160px, 1fr))",
    gap: 16,
    padding: "0 18px 18px",
  },
  footerColTitle: { fontWeight: 700, marginBottom: 10 },
  footerLink: {
    display: "block",
    color: "#0b1220",
    textDecoration: "none",
    marginBottom: 6,
    fontSize: 14,
    opacity: 0.9,
  },
  footerBottom: {
    borderTop: "1px solid #e2e8f0",
    padding: "10px 18px",
    display: "flex",
    justifyContent: "space-between",
    gap: 12,
    color: "#475569",
    fontSize: 13,
  },

  modalWrap: {
    position: "fixed",
    inset: 0,
    background: "rgba(2,6,23,.45)",
    display: "grid",
    placeItems: "center",
    zIndex: 50,
  },
  modal: {
    width: "min(420px, 92vw)",
    background: "white",
    border: "1px solid #d7efef",
    borderRadius: 14,
    padding: 16,
    boxShadow: "0 12px 32px rgba(2,6,23,.35)",
  },
  modalHeader: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
  },
  modalTitle: { fontWeight: 700 },
  modalClose: {
    border: "none",
    background: "transparent",
    fontSize: 18,
    lineHeight: 1,
    cursor: "pointer",
    color: "#334155",
  },
};
